# Prettier friendly markdownlint config (all formatting rules disabled)
extends: markdownlint/style/prettier

# MD033/no-inline-html : Inline HTML : https://github.com/DavidAnson/markdownlint/blob/v0.37.4/doc/md033.md
MD033:
  # Allowed elements
  allowed_elements: [a, i]
